'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OfferLetter
    
    '''<summary>
    '''offerprogress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents offerprogress As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''lbAcccept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAcccept As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ReportViewer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportViewer1 As Global.Microsoft.Reporting.WebForms.ReportViewer
    
    '''<summary>
    '''ObjectDataSource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ObjectDataSource2 As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''pnlOffer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOffer As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lbacceptanceslip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbacceptanceslip As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fuOfferSlip2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuOfferSlip2 As Global.AjaxControlToolkit.AsyncFileUpload
    
    '''<summary>
    '''btnAcceptOffer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAcceptOffer As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeclineOffer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeclineOffer As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfirmPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmPopUp As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfirmPopUp_ModalPopupExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmPopUp_ModalPopupExtender As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''ResultPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResultPopup As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblAppSubmitResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAppSubmitResult As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hideModalPopupViaServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hideModalPopupViaServer As Global.System.Web.UI.WebControls.Button
End Class
